config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contacts
  resources :phones

   root to: "contacts#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :contacts

	
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :addresses, :dependent => :destroy
	accepts_nested_attributes_for :addresses, allow_destroy: true

	belongs_to :user


	has_many :phones, :dependent => :destroy
	accepts_nested_attributes_for :phones, allow_destroy: true

	validates_associated :phones
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :contact


	validates_numericality_of :phone_number
	validates_length_of :phone_number, is: 10
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	
	before_action :authenticate_user!
	def index
		@contacts = current_user.contacts
	end

	def new
		@contact = Contact.new
		@phone = Phone.new
	end
	
	def show
		@contact = Contact.find(params[:id])
	end

	def create
		@contact = Contact.new(contact_params)
		@contact.user_id = current_user.id

		respond_to do |format|
			if @contact.save
				format.html { redirect_to contacts_url, notice: 'Contact was successfully created.' }
				
			else
				format.html { render :new }
			end
		end
	end

	def edit
		@contact = Contact.find(params[:id])
	end
	def update
		@contact = Contact.find(params[:id])
		if @contact.update_attributes(contact_params)
			redirect_to contact_path(@contact.id), notice: "Successfully updated"
		else 
			render action: "edit"
		end
	end
	def destroy
		@contact = Contact.find(params[:id])
		@contact.destroy
		redirect_to contacts_path, notice: "Successfull deleted #{@contact.first_name}"
	end

	private
	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :phones_attributes => [:id, :phone_number, :_destroy], :addresses_attributes => [:id, :address, :country, :_destroy])
	end




end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
	def new
		@phone = Phone.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= nested_form_for (@contact) do |f| %>

<% if @contact.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

  <ul>
    <% @contact.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>





<div class="page-header">
  <h3> Add Contact </h3>
</div>
<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>
<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>




<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">                  <span class="label label-default">Address</span></a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><span class="label label-default">Phone</span></a></li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">


      <h3> Add Address </h3>
      <div class="field">

        <%= f.fields_for :addresses do |li| %>
        <%= li.text_field :address %>

        <%= li.link_to_remove "Remove item" %>
        <% end %>
        <%= f.link_to_add "Add Address ", :addresses %>


        <h3> Add Country </h3>


        <%= f.fields_for :addresses do |li| %>
        <%= li.text_field :country %>

        <%= li.link_to_remove "Remove item" %>
        <% end %>
        <%= f.link_to_add "Add Country ", :addresses %>
      </div>




    </div>



    <div role="tabpanel" class="tab-pane" id="profile">

      <h4> Add Phone Number </h4>
      <div class="field">

        <%= f.fields_for :phones do |li| %>
        <%= li.text_field :phone_number %>

        <%= li.link_to_remove "Remove item" %>
        <% end %>
        <%= f.link_to_add "Add Phone Number ", :phones %>

      </div>

    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<h1> Edit Contact </h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="page-header">
      <h1>All Contacts</h1>
    </div>
    <% if @contacts.empty? %>
    <p>No Contacts Found </p>
    <% else %>
    <table class="table" "table-stiped">
      <thead >
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th> Phone </th>
          <th> Address </th>
          <th> Country </th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.first_name %></td>
          <td><%= contact.last_name %></td>
          <td><%= contact.phones.pluck(:phone_number).join(', ') %></td>
          <td><%= contact.addresses.pluck(:address).join(',') %></td>
          <td><%= contact.addresses.pluck(:country).join(',') %></td>
          <td><%= link_to 'Show', contact %></td>
          <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
          <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <% end %>
  </div>


  <div class="col-md-4">
  <div class="page-header">
  <h3> Add Contact </h3>
  </div>

    <%= link_to 'New Contact', new_contact_path, class: "btn btn-success" %>
  </div>
</div>

app/views/contacts/new.html.erb
<h1> New Contact </h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @contact.last_name %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Contactmanagement</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


	
</head>
<body>
	<% if user_signed_in? %>



	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Contact Management</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">




					<li <%= controller.controller_name == "Contacts" ? "class=active dropdown" : "class=dropdown" %>>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacts<span class="badge"><%= current_user.contacts.size %></span> <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to contacts_path do %>
								<span class="glyphicon glyphicon-th-list"></span>List All
								<% end %>   	

							</li>
							<li>
								<%= link_to new_contact_path do %>
								<span class="glyphicon glyphicon-plus"></span>Add Contact
								<% end %>

							</li>
						</ul>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						
						
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Account Settings", edit_user_registration_path %></li>
								<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

							</ul>
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>





		<h3>Welcome <%= current_user.email %></h3>
		

		
		<% else %>
		<%= link_to "Login", new_user_session_path %> |
		<%= link_to "Sign Up", new_user_registration_path %>
		<% end %>


		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>


	</body>
	</html>

app/views/phones/new.html.erb
<h2>Add Number</h2>


<%= render 'form' %>

<%= link_to 'Back', phones_path %>